"""Add workload fields to route assignments

Revision ID: 29c51dad9f95
Revises: 7993a9174aba
Create Date: 2026-07-11 16:52:19.375264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c51dad9f95'
down_revision: Union[str, Sequence[str], None] = '7993a9174aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_assignments', sa.Column('dps', sa.Integer(), nullable=False))
    op.add_column('route_assignments', sa.Column('parcels', sa.Integer(), nullable=False))
    op.add_column('route_assignments', sa.Column('accountables', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_assignments', 'accountables')
    op.drop_column('route_assignments', 'parcels')
    op.drop_column('route_assignments', 'dps')
    # ### end Alembic commands ###
